### ISSUE TITLE
Doesn't work for swift project

### ISSUE THREAD

**Issue by gerchicov-bp** [BlueCocoa/class-dump#2]
2017-08-10 12:50:56.323 class-dump[37963:221855] Error: Cannot find offset for address 0x4800000001007fed in stringAtAddress:

**Comment by BlueCocoa** [comment]
A nice try. However, there isn't ANY `Error: Cannot find offset for address` string in this repo.

**Comment by gerchicov-bp** [comment]
Thanks but I've already found the reason - previously I somehow installed class-dump and now use the old version instead of the new one with swift fixes (forgot to add "./")
